name: Go

on:
  workflow_dispatch

jobs:

  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Build
      run: go build -ldflags "-s -w -H windowsgui" -o dist/pushcat-amd64.exe

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: pushcat-bin
        path: dist
